plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.moquette:moquette-broker:0.17'
    implementation 'org.slf4j:slf4j-simple:2.0.13'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
}

application {
    mainClass = 'Broker'
    // Herramientas de prueba: Broker (principal), Espia, PublicaPrueba
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
